### ISSUE TITLE
Armor Stand

### ISSUE THREAD

**Issue by Kade-N** [KyleNecrowolf/Revival#19]
Missing texture.

For some reason the default texture is present in the pack files...

![image](https://cloud.githubusercontent.com/assets/20824272/26467644/8db0f72a-4161-11e7-89d7-eba38e83dec4.png)

![wood](https://cloud.githubusercontent.com/assets/20824272/26467760/e90531ea-4161-11e7-8bf6-f5d6614124e9.png)

**Comment by Maisa85** [comment]
Here is one made with birch wood

![wood](https://user-images.githubusercontent.com/29552408/38034129-47d451c6-32aa-11e8-9bcc-e8c23c37c403.png)
![stand](https://user-images.githubusercontent.com/29552408/38034226-78545274-32aa-11e8-9a6f-c3bf99f864a7.png)

**Comment by Maisa85** [comment]
And here another, darker one, which I use.
![wood](https://user-images.githubusercontent.com/29552408/38037560-d04d0cbc-32b1-11e8-8391-c13daba10fe1.png)
![stand1](https://user-images.githubusercontent.com/29552408/38037563-d2955394-32b1-11e8-94ee-3f5c7cdef333.png)

**Comment by Kade-N** [comment]
Adding to the pack! The oak one will be default, with the birch in the folder as an alternate.
