### ISSUE TITLE
Spectator GUI icons

### ISSUE THREAD

**Issue by Kade-N** [KyleNecrowolf/Revival#22]
Very minor, but spectator mode has some GUI icons that need textures. 

![spectator_widgets](https://cloud.githubusercontent.com/assets/20824272/26468902/19d06570-4166-11e7-96a3-63be0924554b.png)

**Comment by Maisa85** [comment]
![spectator_widgets](https://user-images.githubusercontent.com/29552408/39406479-f8f961a2-4bbf-11e8-8ef7-74495b717815.png)
