### ISSUE TITLE
Server/World selection GUI arrows

### ISSUE THREAD

**Issue by Kade-N** [KyleNecrowolf/Revival#23]
Also minor, the singleplayer/multiplayer server/world selection buttons are missing some textures. 

These are almost the same as the resource pack selection buttons, just slightly repositioned. 

Revival resource pack selection arrows:
![resource_packs](https://cloud.githubusercontent.com/assets/20824272/26469013/84f58b50-4166-11e7-982f-f8799353d0ee.png)

Missing arrows:
server_selection
![server_selection](https://cloud.githubusercontent.com/assets/20824272/26469023/9026955a-4166-11e7-8ee7-c80024c47979.png)
world_selection
![world_selection](https://cloud.githubusercontent.com/assets/20824272/26469039/9f0d0040-4166-11e7-9ea2-216b54dc40f7.png)

**Comment by Maisa85** [comment]
Hope these fit

![world_selection](https://user-images.githubusercontent.com/29552408/38026148-a94ba4a2-3293-11e8-850e-1266dfab9c9a.png)
![server_selection](https://user-images.githubusercontent.com/29552408/38026153-ae149944-3293-11e8-8d79-3065ecf3d273.png)

**Comment by Kade-N** [comment]
Yep, looks great! Thanks.
