### ISSUE TITLE
Concrete powder

### ISSUE THREAD

**Issue by Kade-N** [KyleNecrowolf/Revival#45]
I just redid concrete... Concrete powder needs an update as well, to have the right colour palette. I will prob be doing this soon.
![minecraft 1 12 2 4_8 1_07_52 am](https://user-images.githubusercontent.com/20824272/38475828-8d4c8300-3b78-11e8-8a9b-2e218b09613d.png)
![minecraft 1 12 2 4_8 1_24_41 am](https://user-images.githubusercontent.com/20824272/38475832-90659428-3b78-11e8-80c5-e76a688f031f.png)

**Comment by Maisa85** [comment]
Will these suffice?

![sandandstones](https://user-images.githubusercontent.com/29552408/39406135-6202ca0e-4bba-11e8-9e2f-0b1af9982861.png)

![concrete_powder_yellow](https://user-images.githubusercontent.com/29552408/39406114-4920a39e-4bba-11e8-8dd7-9b57fc6d9560.png)
![concrete_powder_black](https://user-images.githubusercontent.com/29552408/39406115-4941db4a-4bba-11e8-8172-db24b95ef220.png)
![concrete_powder_blue](https://user-images.githubusercontent.com/29552408/39406116-4964d0fa-4bba-11e8-9b2f-490cf6f347bd.png)
![concrete_powder_brown](https://user-images.githubusercontent.com/29552408/39406117-498394cc-4bba-11e8-885a-a05404f87754.png)
![concrete_powder_cyan](https://user-images.githubusercontent.com/29552408/39406118-49a14fbc-4bba-11e8-863b-ef8807fdf1bd.png)
![concrete_powder_gray](https://user-images.githubusercontent.com/29552408/39406119-49d81aa6-4bba-11e8-9b60-c5dd4f0f13a5.png)
![concrete_powder_green](https://user-images.githubusercontent.com/29552408/39406120-49f58956-4bba-11e8-9195-119e1b9c9552.png)
![concrete_powder_light_blue](https://user-images.githubusercontent.com/29552408/39406121-4a138370-4bba-11e8-8190-162e8b6575d3.png)
![concrete_powder_lime](https://user-images.githubusercontent.com/29552408/39406122-4a3109f4-4bba-11e8-8fae-3f0abdd98655.png)
![concrete_powder_magenta](https://user-images.githubusercontent.com/29552408/39406123-4a656492-4bba-11e8-942f-b591700efce9.png)
![concrete_powder_orange](https://user-images.githubusercontent.com/29552408/39406124-4a815b02-4bba-11e8-9d59-5f47ba321424.png)
![concrete_powder_pink](https://user-images.githubusercontent.com/29552408/39406125-4a9ebe04-4bba-11e8-9f75-6eabefb0b655.png)
![concrete_powder_purple](https://user-images.githubusercontent.com/29552408/39406126-4abc2d86-4bba-11e8-945a-0e4035982823.png)
![concrete_powder_red](https://user-images.githubusercontent.com/29552408/39406127-4ad94b78-4bba-11e8-8d46-28556c72bcac.png)
![concrete_powder_silver](https://user-images.githubusercontent.com/29552408/39406128-4af67914-4bba-11e8-8511-2cddfc5be927.png)
![concrete_powder_white](https://user-images.githubusercontent.com/29552408/39406129-4b15210c-4bba-11e8-82b2-eb40800d1b4e.png)
