### ISSUE TITLE
Lite version

### ISSUE THREAD

**Issue by Kade-N** [KyleNecrowolf/Revival#48]
Planning to make a lite version of the pack that does not include alternate textures or any OptiFine/MCPatcher features.
This will primarily be for server download, to allow people with slower connections and/or no optifine to download the pack more easily, as the full pack with CTM is quite large. 

It won't be a separate pack or anything, just a separate zip without the extra textures.

If there's not much difference in-game, I won't bother. We've just been noticing pretty significant lag spikes for players using the pack downloaded on our server.

**Comment by Maisa85** [comment]
I have one made already for myself, I will just adjust it a bit and remove all mix-up textures. Shouldn't take long.

**Comment by Kade-N** [comment]
Got this set up with a build script (like the current auto-updated pack zip), will be posting download links soon. 
I have two planned right now. One contains only CIT (custom item textures), intended mostly for our own server. The other is the lite version will all Optifine/MCPatcher textures stripped out.
