### ISSUE TITLE
Key

### ISSUE THREAD

**Issue by Kade-N** [KyleNecrowolf/Revival#58]
Custom key item, intended to be used with locked chests (built into the game). Will be CIT based on sticks.

**Comment by Maisa85** [comment]
2018-05-09 2:02 GMT+03:00 Kyle Nanakdewa <notifications@github.com>:

**Comment by Maisa85** [comment]
Ok let's try again, the answering through gmail doesn't work with attachments. 

![key0](https://user-images.githubusercontent.com/29552408/43191065-161f33e2-9003-11e8-960e-f5202afc336f.png)
