### ISSUE TITLE
Door Items

### ISSUE THREAD

**Issue by actioninja** [KyleNecrowolf/Revival#61]
All the new wood door types are good in the block version, but the items are still untextured.

- [ ] `door_spruce.png`
- [ ] `door_birch.png`
- [ ] `door_jungle.png`
- [ ] `door_acacia.png`
- [ ] `door_dark_oak.png`

**Comment by Kade-N** [comment]
Rihawk sent us some... just got to add them

**Comment by Maisa85** [comment]
Here's what I've made previously
![door_acacia](https://user-images.githubusercontent.com/29552408/43190824-9d493d3c-9002-11e8-998c-e3babcc238b5.png)
![door_birch](https://user-images.githubusercontent.com/29552408/43190825-9d643b28-9002-11e8-8565-ddcbea277d42.png)
![door_dark_oak](https://user-images.githubusercontent.com/29552408/43190826-9d804138-9002-11e8-9ffa-94b8c3db6311.png)
![door_jungle](https://user-images.githubusercontent.com/29552408/43190828-9d9e086c-9002-11e8-85db-88a719fa2816.png)
![door_spruce](https://user-images.githubusercontent.com/29552408/43190829-9dba6a48-9002-11e8-804a-878a81ceb316.png)

**Comment by actioninja** [comment]
closed by mistake, but do you mind if I add those in a pull request?  With credit of course, just to get them in a bit quicker.

**Comment by Maisa85** [comment]
Sure, do what ever needs to be done. I don't mind the credits in what I do for this pack, I just modify/copy/rearrange the textures that someone else has done already.

**Comment by Kade-N** [comment]
Doors added to 1.14 branch.
