### ISSUE TITLE
Ender Chests

### ISSUE THREAD

**Issue by Kade-N** [KyleNecrowolf/Revival#81]
![image](https://user-images.githubusercontent.com/20824272/172224040-3145420a-4853-4a35-a9dd-92e864e75d93.png)

Seems like a MC update broke them, there's some z-fighting at the bottom edge of the lid, and the Ender Chest texture doesn't seem to be the right one

**Comment by PixelatedVolume** [comment]
Pretty sure I have a fix for this already but I'll need to check.

**Comment by Kade-N** [comment]
Chests were fixed a while back
I think I still need to do Ender Chests

**Comment by Kade-N** [comment]
Fixed in aa816e0453508f12ce7a9787f6aa9b743dec6d02
